[project]
name = "tmm-jax"
version = "0.1.0"
description = "A fast TMM optimizer based on jax"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jax>=0.7.0",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "scipy>=1.16.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.7",
]
